export enum QUERY_KEY {
  FUNDING_REQUESTS = "QUERY:FUNDING_REQUESTS",
  FUNDING_REQUEST = "QUERY:FUNDING_REQUEST",
  ENTERPRISE_BALANCE = "QUERY:ENTERPRISE_BALANCE",
  LUNA_BALANCE = "QUERY:LUNA_BALANCE",
  CW20_BALANCE = "QUERY:CW20_BALANCE",
  CW20_TOKENS = "QUERY:CW20_TOKENS",
  NATIVE_TOKENS = "QUERY:NATIVE_TOKENS",
  IBC_TOKENS = "QUERY:IBC_TOKENS",
  PRICES = "QUERY:PRICES",
}
